# 1. 准备数据

In [1]:
import os 
import pandas as pd

In [2]:
"""
函数功能：得到标记好的数据集
"""
def get_train():
    path = 'digit/trainingDigits'
    trainingFileList = os.listdir(path)
    train = pd.DataFrame()
    img = []
    labels = []
    for i in range(len(trainingFileList)):
        filename = trainingFileList[i]
        txt = pd.read_csv(f'digit/trainingDigits/{filename}',header = None)
        num = ''
        for i in range(txt.shape[0]):
             num += txt.iloc[i,:]
        img.append(num[0])
        filelabel = filename.split('_')[0]
        labels.append(filelabel)
    train['img'] = img
    train['labels'] = labels
    return train

In [3]:
train = get_train()

In [4]:
train.head()

                                                 img labels
0  0000000000000111100000000000000000000000000011...      0
1  0000000000011111000000000000000000000000001111...      0
2  0000000000000011000000000000000000000000000001...      0
3  0000000000001111000000000000000000000000000111...      0
4  0000000000000011111000000000000000000000000011...      0

In [5]:
train.iloc[:,-1]. value_counts()

9    204
7    201
3    199
1    198
6    195
2    195
0    189
5    187
4    186
8    180
Name: labels, dtype: int64

In [6]:
len(train.iloc[1,0])

1024

In [7]:
"""
函数功能：得到标记好的测试集
"""
def get_test():
    path = 'digit/testDigits'
    testFileList = os.listdir(path)
    test = pd.DataFrame()
    img = []
    labels = []
    for i in range(len(testFileList)):
        filename = testFileList[i]
        txt = pd.read_csv(f'digit/testDigits/{filename}',header = None)
        num = ''
        for i in range(txt.shape[0]):
             num += txt.iloc[i,:]
        img.append(num[0])
        filelabel = filename.split('_')[0]
        labels.append(filelabel)
    test['img'] = img
    test['labels'] = labels
    return test

In [8]:
test = get_test()

In [ ]:
t

# 2.分类器代码的构建

In [9]:
import Levenshtein

距离计算公式，使用hamming距离：计算两个等长字串之间对应位置上不同字符的个数，要求输入的两个字符串必须长度一致

In [10]:
from Levenshtein import hamming
# Levenshtein.hamming(str1,str2) #汉明距离格式

构建分类器

In [11]:
"""
函数功能：k-近邻算法实现手写数字分类
参数说明：
train：训练集
test： 测试集
k：k-近邻参数，即选择距离最小的k个点
返回：预测好分类的测试集
"""
def handwritingClass(train, test, k):
    n = train.shape[0]
    m = test.shape[0]
    result = []
    for i in range(m):
        dist = []
        for j in range(n):
            d = str(hamming(train.iloc[j,0],test.iloc[i,0]))
            dist.append(d)
        dist_l = pd.DataFrame({'dist':dist, 'labels':(train.iloc[:,1])})
        dr = dist_l.sort_values(by = 'dist')[:k]
        re = dr.loc[:, 'labels'].value_counts()
        result.append(re.index[0])
    result = pd.Series(result)
    test['predict'] = result
    acc = (test.iloc[:,-1]) == test.iloc[:,-2].mean()
    print(f'模型预测准确率为{acc}')
    return test

In [12]:
handwritingClass(train,test,3)

模型预测准确率为0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
916    False
917    False
918    False
919    False
920    False
921    False
922    False
923    False
924    False
925    False
926    False
927    False
928    False
929    False
930    False
931    False
932    False
933    False
934    False
935    False
936    False
937    False
938    False
939    False
940    False
941    False
942    False
943    False
944    False
945    False
Name: predict, Length: 946, dtype: bool

                                                   img labels predict
0    0000000000000110000000000000000000000000000011...      0       0
1    0000000000000001100000000000000000000000000111...      0       0
2    0000000000010000000000000000000000000000001111...      0       0
3    0000000000000010110000000000000000000000000011...      0       0
4    0000000000000000011100000000000000000000000000...      0       0
5    0000000000000011110000000000000000000000000011...      0       0
6    0000000000000011110000000000000000000000000001...      0       0
7    0000000000000011111000000000000000000000000011...      0       0
8    0000000000010000000000000000000000000000001100...      0       0
9    0000000000000110000000000000000000000000000111...      0       0
10   0000000000000001110000000000000000000000000001...      0       0
11   0000000000000111000000000000000000000000000011...      0       0
12   0000000000001000000000000000000000000000001111...      0       0
13   0000000000000001000000000000000000000000000000...      0       0
14   0000000000000001000000000000000000000000000001...      0       0
15   0000000000000011010000000000000000000000000001...      0       0
16   0000000000000011110000000000000000000000000001...      0       0
17   0000000000000011111000000000000000000000000001...      0       0
18   0000000000000000001000000000000000000000001110...      0       0
19   0000000000001111111100000000000000000000000111...      0       0
20   0000000000011111111000000000000000000000001111...      0       0
21   0000000000000000000000000000000000000000001111...      0       0
22   0000000000000111000000000000000000000000000111...      0       0
23   0000000000000110000000000000000000000000000000...      0       0
24   0000000000000110000000000000000000000000001111...      0       0
25   0000000000000011110000000000000000000000000001...      0       0
26   0000000000001110000000000000000000000000000111...      0       0
27   0000000000001110000000000000000000000000000111...      0       0
28   0000000000000011111000000000000000000000000000...      0       0
29   0000000000000010000000000000000000000000000111...      0       0
..                                                 ...    ...     ...
916  0000000000000011111000000000000000000000000011...      9       9
917  0000000000000000111110000000000000000000000000...      9       9
918  0000000000000000111111000000000000000000000000...      9       9
919  0000000000000000000001000000000000000000000000...      9       9
920  0000000000000000100000000000000000000000000000...      9       9
921  0000000000001111111110000000000000000000001111...      9       9
922  0000000000000011111111110000000000000000000001...      9       9
923  0000000000000000001111000000000000000000000000...      9       9
924  0000000000000001110000000000000000000000000001...      9       9
925  0000000000011100000000000000000000000000001111...      9       9
926  0000000000001111100000000000000000000000000111...      9       9
927  0000000000000111110000000000000000000000000111...      9       9
928  0000000000111111110000000000000000000000011111...      9       9
929  0000000000000111000000000000000000000000001111...      9       9
930  0000000000000000001000000000000000000000000000...      9       9
931  0000000000000000000111111000000000000000000000...      9       9
932  0000000000000001100000000000000000000000000011...      9       9
933  0000000000011111111110000000000000000000111111...      9       9
934  0000000000001111111100000000000000000000000111...      9       9
935  0000000000000011111110000000000000000000000011...      9       9
936  0000000000001111111000000000000000000000000111...      9       9
937  0000000000011111110000000000000000000000011111...      9       9
938  0000000000001111111111000000000000000000011111...      9       9
939  0000000000000000000011100000000000000000000000...      9       9
940  0000000000000000001111000000000000000000000000...      9       9
941  0000000000000000000000011100000000000000000000...      9       9
942  0000000000000111110000000000000000000000000001...      9       9
943  0000000000111111000000000000000000000000111111...      9       9
944  0000000000111111111000000000000000000000011111...      9       9
945  0000000000000000001111110000000000000000000000...      9       9

[946 rows x 3 columns]